export interface Character {
    nombre: string,
    apodo: string,
    altura: string,
    peso: string,
    edad: string,
    raza: string,
    genero: string,
    sexualidad: string,
    historia: string,
    debilidad: string,
    gustos: string,
    alineamiento: string,
    poderes: string,
    equipamiento: string,
    extra: string,
    ostglobal: string,
    ostbatalla: string,
    ostsentimental: string,
    apariencia: string,
}